# This file is generated by `pnpm run build:binary` — do not edit by hand.
# To regenerate: pnpm run build:binary
provider_installation {
  dev_overrides {
    "example/dummycloud" = "__BIN_DIR__"
  }
  direct {}
}
